SurveyTool/Controllers/ResponsesController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SurveyTool.Models;

namespace SurveyTool.Controllers
{
    [Authorize]
    public class ResponsesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public ResponsesController(ApplicationDbContext db)
        {
            _db = db;
        }

        [HttpGet]
        public ActionResult Index(int surveyId)
        {
            var responses = _db.Responses
                               .Include("Survey")
                               .Include("Answers")
                               .Include("Answers.Question")
                               .Where(x => x.SurveyId == surveyId)
                               .Where(x => x.CreatedBy == User.Identity.Name)
                               .OrderByDescending(x => x.CreatedOn)
                               .ThenByDescending(x => x.Id)
                               .ToList();

            return View(responses);
        }

        [HttpGet]
        public ActionResult Details(int surveyId, int id)
        {
            var response = _db.Responses
                              .Include("Survey")
                              .Include("Answers")
                              .Include("Answers.Question")
                              .Where(x => x.SurveyId == surveyId)
                              .Where(x => x.CreatedBy == User.Identity.Name)
                              .Single(x => x.Id == id);

            response.Answers = response.Answers.OrderBy(x => x.Question.Priority).ToList();
            return View(response);
        }

        [HttpGet]
        public ActionResult Create(int surveyId)
        {
            var survey = _db.Surveys
                            .Where(s => s.Id == surveyId)
                            .Select(s => new
                                {
                                    Survey = s,
                                    Questions = s.Questions
                                                 .Where(q => q.IsActive)
                                                 .OrderBy(q => q.Priority)
                                })
                             .AsEnumerable()
                             .Select(x =>
                                 {
                                     x.Survey.Questions = x.Questions.ToList();
                                     return x.Survey;
                                 })
                             .Single();

            return View(survey);
        }

        [HttpPost]
        public ActionResult Create(int surveyId, string action, Response model)
        {
            model.Answers = model.Answers.Where(a => !String.IsNullOrEmpty(a.Value)).ToList();
            model.SurveyId = surveyId;
            model.CreatedBy = User.Identity.Name;
            model.CreatedOn = DateTime.Now;
            _db.Responses.Add(model);
            _db.SaveChanges();

            TempData["success"] = "Your response was successfully saved!";

            return action == "Next"
                       ? RedirectToAction("Create", new {surveyId})
                       : RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public ActionResult Delete(int surveyId, int id, string returnTo)
        {
            var response = new Response() { Id = id, SurveyId = surveyId };
            _db.Entry(response).State = EntityState.Deleted;
            _db.SaveChanges();
            return Redirect(returnTo ?? Url.RouteUrl("Root"));
        }
    }
}

SurveyTool/Views/Responses/Create.cshtml
@model SurveyTool.Models.Survey

@{
    ViewBag.Title = Model.Name;
}

@section Scripts
{
    <script type="text/javascript">
        $(function() {
            $('.datepicker').datepicker({format: 'mm/dd/yyyy'});

            $(document).on('click', 'a[data-toggle=comment]', function() {
                var id = $(this).attr('href');
                $(id).toggle();
                return false;
            });
        });
    </script>
}

<div class="page-header">
    <h3>@ViewBag.Title</h3>
</div>

<form action="@Url.Action("Create", "Responses", new {surveyId = Request["surveyId"]})" method="post">
    <div class="well well-small">
        <h4>Questions</h4>
    </div>
    <ul class="unstyled bordered skip-first">
        @foreach (var question in Model.Questions)
        {
            <li class="row">
                <div class="span9">
                    <input type="hidden" name="Answers.Index" value="@question.Id" />
                    <input type="hidden" name="Answers[@question.Id].QuestionId" value="@question.Id" />
                    @Html.Raw(question.Body)
                </div>
                <div class="span3">
                    @if (question.Type == "Yes/No")
                    {
                        <select class="span3" name="Answers[@question.Id].Value">
                            <option disabled selected>Select a value...</option>
                            <option>Yes</option>
                            <option>No</option>
                        </select>
                    }
                    @if (question.Type == "Number")
                    {
                        <input class="span3" type="text" name="Answers[@question.Id].Value" placeholder="Enter a number..." />
                    }
                    <textarea id="@("comment" + question.Id)" class="span3 hide" name="Answers[@question.Id].Comment" placeholder="Comments..."></textarea>
                    <a href="@("#comment" + @question.Id)" data-toggle="comment"><small>Show/Hide Comment</small></a>
                </div>
            </li>
        }
    </ul>
    
    <div class="form-actions">
        <button class="btn btn-inverse pull-right" name="action" value="Next">
            Save and Enter Another
        </button>
        <input class="btn btn-primary" type="submit" name="action" value="Save" />
        <a class="btn" href="@Url.Action("Index", "Home")">Cancel</a>
    </div>
</form>

SurveyTool/Views/Responses/Details.cshtml
@model SurveyTool.Models.Response

@{
    ViewBag.Title = Model.Survey.Name;
}

<div class="page-header">
    <h3>@ViewBag.Title</h3>
</div>

<div class="well well-small">
    <h4>Response Information</h4>
</div>
<ul class="unstyled bordered skip-first">
    <li class="row">
        <div class="span9">
            <label><b>User</b></label>
            <p class="help-block">
                The user that completed this survey.
            </p>
        </div>
        <div class="span3">
            <div class="well well-small">
                @Model.CreatedBy
            </div>
        </div>
    </li>
    <li class="row">
        <div class="span9">
            <label><b>Survey Date</b></label>
            <p class="help-block">
                The date on which the audit occurred.
            </p>
        </div>
        <div class="span3">
            <div class="well well-small">
                @Model.CreatedOn.ToString("d")
            </div>
        </div>
    </li>
</ul>

<div class="well well-small">
    <h4>Questions</h4>
</div>
<ul class="unstyled bordered skip-first">
    @foreach (var item in Model.Answers)
    {
        <li class="row">
            <div class="span9">
                @Html.Raw(item.Question.Body)
            </div>
            <div class="span3">
                <div class="well well-small">@item.Value</div>
                <div class="well well-small">@item.Comment</div>
            </div>
        </li>
    }
</ul>

SurveyTool/Views/Responses/Index.cshtml
@model IEnumerable<SurveyTool.Models.Response>

@{
    ViewBag.Title = "Responses";
}

@section scripts
{
    @Scripts.Render("~/bundles/models")

    <script type="text/javascript">
        $(function () {
            ko.applyBindings(new ResponseListModel(), $('#response-list')[0]);
        })
    </script>
}

<div class="page-header">
    <h2>Responses <small>Manage survey responses</small></h2>
</div>

<table id="response-list" class="table table-striped">
    <thead>
        <tr>
            <th class="span1">Date</th>
            <th class="span6">Survey</th>
            <th class="span2">Team Member</th>
            <th class="span2">Results</th>
            <th class="span1">Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td><span class="muted">@item.CreatedOn.ToString("d")</span></td>
                <td>
                    <a href="@Url.Action("Details", "Responses", new {surveyId = item.SurveyId, id = item.Id})">
                        @item.Survey.Name
                    </a>
                </td>
                <td>
                    @item.CreatedBy
                </td>
                <td>
                    @item.GetAnswerCount()/@item.GetQuestionCount() - 
                    @item.CalculateScore().ToString("P1")
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete",
                                     new { Controller = "Responses", surveyId = item.SurveyId, id = item.Id },
                                     new { @class = "text-error", data_bind = "click: destroy" })
                </td>
            </tr>
        }
    </tbody>
</table>